name: Scheduled JavaScript Run

on:
  schedule:
    - cron: '0 1 * * *'  # 每天午夜运行
  workflow_dispatch:
  
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'  # 您可以选择其他版本
    - name: Install dependencies
      run: npm ci  # 如果您的项目有 package.json
    - name: Run script
      run: node index.js
